# Generated by Django 4.1.4 on 2023-01-16 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=40)),
                ('created_att', models.DateTimeField(auto_now_add=True)),
                ('updated_att', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=560)),
                ('product', models.CharField(max_length=160)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_Price', models.IntegerField()),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=560)),
                ('product', models.CharField(max_length=160)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Medisice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=160)),
                ('price', models.IntegerField(default=0)),
                ('quatity', models.IntegerField(default=0)),
                ('exire_date', models.DateField()),
                ('medicine_img', models.ImageField(upload_to='medicine_pic')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacey_App.catagory')),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacey_App.suplier')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quntity', models.IntegerField()),
                ('sale_date', models.DateField(auto_now=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sele_medicine', to='Pharmacey_App.medicine')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacey_App.client')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pharmacey_App.stock_medisice'),
        ),
    ]
